<script lang="ts">
  import Sprite from './office/Sprite.svelte';
  export let staff: any[] = [], board: any[] = [], projects: any[] = [], environments: any[] = [];
  export let mode = 'coworkers';
  export let openPerson: (person: any) => void;
  export let openTask: (task: any) => void;
  export let mutate: (path: string, body: any, method?: string) => Promise<void>;
  let ceilings: Record<string,string> = {};
  let filter = 'All', project = '', employee = '', status = '';
  $: people = staff.filter(p => filter === 'All' || (filter === 'Remote' ? p.environment.kind === 'coder' : p.environment.kind === 'local'));
  $: tasks = board.filter(t => (!project || t.project_id === project) && (!employee || (employee === 'unassigned' ? !t.employee_id : t.employee_id === employee)) && (!status || t.working_state === status));
  $: lanes = [
    {label:'To do', tasks:tasks.filter(task=>['planned','blocked','waiting for capacity'].includes(task.working_state))},
    {label:'In progress', tasks:tasks.filter(task=>task.working_state==='working')},
    {label:'Done', tasks:tasks.filter(task=>task.working_state==='complete')},
    {label:'Cancelled', tasks:tasks.filter(task=>task.working_state==='cancelled')}
  ];
  function work(person: any) { return board.find(t => t.task_id === person.assignment?.task_id); }
</script>
<section class="directory">
  <header><p>ACROSS YOUR PROJECTS</p><h1>{mode === 'board' ? 'Office task board' : 'Coworkers'}</h1><span>{mode === 'board' ? 'Every task, its owner, and what needs to happen next.' : 'Available and assigned coworkers, wherever they work.'}</span></header>
  {#if mode === 'coworkers'}
    <nav aria-label="Coworker filters">{#each ['All','In office','Remote'] as value}<button aria-pressed={filter === value} onclick={() => filter = value}>{value}</button>{/each}</nav>
    <div class="people">{#each people as person}<article>
      <button class="person" onclick={() => openPerson(person)}><div class="sprite"><Sprite character kind="standing" recipe={person.appearance_recipe}/></div><div><h2>{person.name}</h2><p>{person.title}</p><strong>{person.environment.kind === 'local' ? 'In office · Local' : 'Remote · Coder'}{person.environment.fixture ? ' · Fixture' : ''}</strong><p>{person.environment.name} · {person.environment.health}</p><p>{person.assignment ? `${person.assignment.project_name} / ${person.assignment.task_title}` : 'Available for assignment'}</p><span>{work(person)?.working_state || (person.active ? 'Available' : 'Inactive')}{work(person)?.blocking_reason ? ` · ${work(person).blocking_reason}` : ''}</span></div></button>
      <label>Execution location<select aria-label={`Location for ${person.name}`} value={person.environment.environment_id} onchange={e => mutate(`/staff/${person.employee_id}/environment`, {environment_id:e.currentTarget.value})}>{#each environments as env}<option value={env.environment_id}>{env.name} · {env.kind} · {env.health}</option>{/each}</select></label>
    </article>{/each}</div>
    {#if !people.length}<p class="empty">No coworkers in this view.</p>{/if}
    <details><summary>Configure a remote location</summary><p>Coder connections and execution arrive in milestone 6. Saved locations are not connected.</p><form onsubmit={e => {e.preventDefault();const form=e.currentTarget;void mutate('/environments',{name:new FormData(form).get('name')},'POST').then(()=>form.reset());}}><input name="name" aria-label="Remote location name" placeholder="Coder workspace name" required/><button>Save remote location</button></form></details>
  {:else}
    <nav class="filters" aria-label="Task board filters"><label>Project<select bind:value={project}><option value="">All projects</option>{#each projects as p}<option value={p.project_id}>{p.name}</option>{/each}</select></label><label>Coworker<select bind:value={employee}><option value="">All coworkers</option><option value="unassigned">Unassigned</option>{#each staff as p}<option value={p.employee_id}>{p.name}</option>{/each}</select></label><label>Status<select bind:value={status}><option value="">All statuses</option>{#each ['planned','working','complete','blocked','waiting for capacity'] as s}<option>{s}</option>{/each}</select></label></nav>
    <div class="lanes">{#each lanes as lane}<section class="lane"><h2>{lane.label} <small>{lane.tasks.length}</small></h2>{#each lane.tasks as task}<button class="task" onclick={() => openTask(task)}><small>{task.project_name} · {task.working_state}</small><h3>{task.title}</h3><p>Owner · {task.employee_name || 'Unassigned'}</p><p>{task.blocking_reason || task.last_meaningful_update?.summary || 'No action waiting.'}</p><small>Session {task.attempt?.session_id || 'not started'} · updated {task.last_meaningful_update?.at ? new Date(task.last_meaningful_update.at).toLocaleString() : 'unknown'}</small></button>{:else}<p class="lane-empty">No tasks</p>{/each}</section>{/each}</div>
    {#if !tasks.length}<p class="empty">No tasks match these filters.</p>{/if}
  {/if}
  <section class="capacity"><h2>Execution capacity</h2><p>Reservations count sessions and their processes. Saved coworkers do not consume slots. Waiting tasks need an explicit launch retry.</p>{#each environments as env}<details><summary>{env.name}{env.fixture ? ' · Fixture' : ''} · {env.capacity.active} active + {env.capacity.reserved} reserved / {env.capacity.effective_limit} effective slots</summary><p>{env.capacity.reason} Shared host: {env.host_id}.</p><p>Resource limit {env.capacity.resource_limit}; CPU limit {env.capacity.cpu_limit}; memory limit {env.capacity.memory_limit}. Estimate: 2 CPUs and 4 GiB per session including subprocesses.</p><p>{env.capacity.sample?.source || 'No measurement'} · {env.capacity.sample ? new Date(env.capacity.sample.measured_at).toLocaleString() : 'Unknown freshness'} · {env.capacity.fresh ? 'Fresh' : 'Missing or stale'}</p><form onsubmit={e => {e.preventDefault();const value=new FormData(e.currentTarget).get('ceiling');void mutate(`/hosts/${env.host_id}/capacity`,{ceiling:value === '' ? null : Number(value)});}}><label>Lower user ceiling<input name="ceiling" type="number" min="0" step="1" value={ceilings[env.host_id] ?? env.capacity.user_ceiling ?? ''} oninput={e => ceilings={...ceilings,[env.host_id]:e.currentTarget.value}} placeholder="Automatic"/></label><button>Save ceiling</button><button type="button" onclick={()=>{ceilings={...ceilings,[env.host_id]:''};void mutate(`/hosts/${env.host_id}/capacity`,{ceiling:null});}}>Use automatic limit</button></form></details>{/each}</section>
</section>
<style>
.directory{max-width:1200px;margin:8px auto;background:#eee6d6;border:6px solid #d7cdb7;padding:28px;color:#595447}header{border-bottom:1px solid #cdbfa7;padding-bottom:24px}header>p{font-size:10px;letter-spacing:.13em}h1{font-size:28px;margin:8px 0}h2{font-size:17px;margin:0 0 6px}p{margin:5px 0}nav{display:flex;gap:8px;margin:24px 0;flex-wrap:wrap}button,input,select{font:inherit;padding:10px;border:1px solid #bcaf94;border-radius:3px;background:#fff9ed;color:#3b4435}button{cursor:pointer}button[aria-pressed=true]{background:#cbd6bf;border-color:#71815e}.people{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}article{background:#fff9ed;border:1px solid #d4c7b0;padding:16px;min-width:0}.person{display:flex;gap:18px;text-align:left;width:100%;border:0;padding:0;background:none}.person p{font-size:12px}.person strong,.person span{font-size:12px}.sprite{width:48px;min-width:48px;height:80px}label{display:grid;gap:5px;font-size:12px}article label{margin-top:16px}select,input{min-width:0;max-width:100%}.lanes{display:grid;grid-template-columns:repeat(4,minmax(210px,1fr));gap:12px;overflow:auto}.lane{background:#e1d6c0;border:1px solid #c6b99f;padding:12px;min-height:220px}.lane h2{display:flex;justify-content:space-between;border-bottom:1px solid #c6b99f;padding-bottom:9px}.lane h2 small{font-weight:400}.task{display:grid;gap:5px;text-align:left;width:100%;margin:8px 0}.task h3{margin:0;font-size:15px}.task p{font-size:12px}.task small{color:#806a50}.lane-empty{font-size:12px;color:#837765}.capacity{border-top:1px solid #cdbfa7;margin-top:28px;padding-top:24px}.capacity>p{font-size:13px;margin-bottom:16px}details{border-top:1px solid #d4c7b0;padding:14px 0;margin-top:10px}summary{cursor:pointer;font-weight:600}details p{font-size:12px}form{display:flex;align-items:end;gap:8px;margin-top:12px}.empty{padding:24px;border:1px dashed #bcaf94}@media(max-width:800px){.people{grid-template-columns:1fr}.directory{padding:16px}form{flex-wrap:wrap}}
</style>
